In [15]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import BayesianRidge
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict
import warnings
warnings.filterwarnings('ignore')


In [16]:
X_train = np.load('/home/jaco/Downloads/creditcardfraud/np_X_train.npy')
X_test = np.load('/home/jaco/Downloads/creditcardfraud/np_X_test.npy')
X_train_balanced = np.load('/home/jaco/Downloads/creditcardfraud/np_X_train_balanced.npy')
Y_train = np.load('/home/jaco/Downloads/creditcardfraud/np_Y_train.npy')
Y_test = np.load('/home/jaco/Downloads/creditcardfraud/np_Y_test.npy')
Y_train_balanced = np.load('/home/jaco/Downloads/creditcardfraud/np_Y_train_balanced.npy')
X_train_balanced42 = np.load('/home/jaco/Downloads/creditcardfraud/np_X_train_balanced42.npy')
Y_train_balanced42 = np.load('/home/jaco/Downloads/creditcardfraud/np_Y_train_balanced42.npy')
X_train_balanced2 = np.load('/home/jaco/Downloads/creditcardfraud/np_X_train_balanced2.npy')
Y_train_balanced2 = np.load('/home/jaco/Downloads/creditcardfraud/np_Y_train_balanced2.npy')

In [17]:
Classifiers = {
    "Logistic Regression": LogisticRegression(),
    "Ada Boost": AdaBoostClassifier(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier()
}

In [18]:
for key, classifier in Classifiers.items():
    classifier.fit(X_train, Y_train)
    Score = cross_val_score(classifier, X_train, Y_train)
    print('Classifier: ', classifier.__class__.__name__, ': {:.2f}%'.format(round(Score.mean()*100, 2)))

Classifier:  LogisticRegression : 99.89%
Classifier:  AdaBoostClassifier : 99.92%
Classifier:  RandomForestClassifier : 99.95%
Classifier:  KNeighborsClassifier : 99.83%


In [19]:
for key, classifier in Classifiers.items():
    classifier.fit(X_train_balanced, Y_train_balanced)
    Score = cross_val_score(classifier, X_train_balanced, Y_train_balanced)
    print('Classifier: ', classifier.__class__.__name__, ': {:.2f}%'.format(round(Score.mean()*100, 2)))

Classifier:  LogisticRegression : 97.07%
Classifier:  AdaBoostClassifier : 98.45%
Classifier:  RandomForestClassifier : 99.98%
Classifier:  KNeighborsClassifier : 94.79%


In [20]:
for key, classifier in Classifiers.items():
    classifier.fit(X_train_balanced42, Y_train_balanced42)
    Score = cross_val_score(classifier, X_train_balanced42, Y_train_balanced42)
    print('Classifier: ', classifier.__class__.__name__, ': {:.2f}%'.format(round(Score.mean()*100, 2)))

Classifier:  LogisticRegression : 97.18%
Classifier:  AdaBoostClassifier : 98.49%
Classifier:  RandomForestClassifier : 99.98%
Classifier:  KNeighborsClassifier : 94.78%


In [21]:
for key, classifier in Classifiers.items():
    classifier.fit(X_train_balanced2, Y_train_balanced2)
    Score = cross_val_score(classifier, X_train_balanced2, Y_train_balanced2)
    print('Classifier: ', classifier.__class__.__name__, ': {:.2f}%'.format(round(Score.mean()*100, 2)))

Classifier:  LogisticRegression : 96.55%
Classifier:  AdaBoostClassifier : 98.50%
Classifier:  RandomForestClassifier : 99.98%
Classifier:  KNeighborsClassifier : 94.78%


In [32]:
from sklearn.metrics import confusion_matrix

In [34]:
for key, classifier in Classifiers.items():
    classifier_fitted = classifier.fit(X_train_balanced, Y_train_balanced.ravel())
    y_pred = classifier_fitted.predict(X_test)
    print('Classifier: ', classifier.__class__.__name__,'\n', classification_report(Y_test, y_pred))
    print('Confusion Matrix: ', classifier.__class__.__name__,'\n', confusion_matrix(Y_test, y_pred))

Classifier:  LogisticRegression 
               precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     85308
         1.0       0.09      0.84      0.16       135

    accuracy                           0.99     85443
   macro avg       0.54      0.92      0.58     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  LogisticRegression 
 [[84154  1154]
 [   21   114]]
Classifier:  AdaBoostClassifier 
               precision    recall  f1-score   support

         0.0       1.00      0.99      1.00     85308
         1.0       0.13      0.84      0.22       135

    accuracy                           0.99     85443
   macro avg       0.56      0.92      0.61     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  AdaBoostClassifier 
 [[84539   769]
 [   21   114]]
Classifier:  RandomForestClassifier 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00

In [35]:
for key, classifier in Classifiers.items():
    classifier_fitted = classifier.fit(X_train_balanced42, Y_train_balanced42.ravel())
    y_pred = classifier_fitted.predict(X_test)
    print('Classifier: ', classifier.__class__.__name__,'\n', classification_report(Y_test, y_pred))
    print('Confusion Matrix: ', classifier.__class__.__name__,'\n', confusion_matrix(Y_test, y_pred))

Classifier:  LogisticRegression 
               precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     85308
         1.0       0.09      0.84      0.16       135

    accuracy                           0.99     85443
   macro avg       0.55      0.91      0.58     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  LogisticRegression 
 [[84172  1136]
 [   22   113]]
Classifier:  AdaBoostClassifier 
               precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     85308
         1.0       0.12      0.84      0.20       135

    accuracy                           0.99     85443
   macro avg       0.56      0.91      0.60     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  AdaBoostClassifier 
 [[84453   855]
 [   22   113]]
Classifier:  RandomForestClassifier 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00

In [36]:
for key, classifier in Classifiers.items():
    classifier_fitted = classifier.fit(X_train_balanced2, Y_train_balanced2.ravel())
    y_pred = classifier_fitted.predict(X_test)
    print('Classifier: ', classifier.__class__.__name__,'\n', classification_report(Y_test, y_pred))
    print('Confusion Matrix: ', classifier.__class__.__name__,'\n', confusion_matrix(Y_test, y_pred))

Classifier:  LogisticRegression 
               precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     85308
         1.0       0.09      0.84      0.16       135

    accuracy                           0.99     85443
   macro avg       0.54      0.91      0.58     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  LogisticRegression 
 [[84169  1139]
 [   22   113]]
Classifier:  AdaBoostClassifier 
               precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     85308
         1.0       0.11      0.85      0.20       135

    accuracy                           0.99     85443
   macro avg       0.55      0.92      0.59     85443
weighted avg       1.00      0.99      0.99     85443

Confusion Matrix:  AdaBoostClassifier 
 [[84379   929]
 [   20   115]]
Classifier:  RandomForestClassifier 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00